#include "Common.hlsl"
float3 _slicePosition;;
float3 _location;
float _radius;
int _modification;
RWStructuredBuffer<int> _voxels;

#pragma kernel CSMain
[numthreads(4, 4, 4)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float3 voxelPosition = _slicePosition + float3(id.x, id.y, id.z);
    if (distance(voxelPosition, _location) < _radius)
    {
        if (voxelPosition.y > 0.0f)
        {
            _voxels[CalculateVoxelIndex(id)] = _modification;
        }
    }
}
