#include "Common.hlsl"
float3 _worldPosition;
RWStructuredBuffer<int> _voxels;

#pragma kernel CSMain
[numthreads(4, 4, 4)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float3 voxelPosition = _worldPosition + float3(id.x, id.y, id.z);
    float s = sin(voxelPosition.x * 0.05f) * 8.0f;
    float c = cos(voxelPosition.z * 0.08f) * 8.0f;
    _voxels[CalculateVoxelIndex(id)] = (voxelPosition.y + s + c) > 32.0f ? 0 : 1;
}
